name: app_individual
description: "Pomodoro timer with companion."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/icon/app_icon.png"  # ← pon aquí tu PNG (mínimo 1024x1024px)

flutter:
  uses-material-design: true

  assets:
    # Agrega aquí cada sprite que uses
    # - assets/sprites/shime1.png
    # - assets/sprites/shime2.png
    # ...
    # O declara la carpeta entera así:
    - assets/sprites/
    - assets/emptycat.png
    - assets/filledcat.png
    